config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :campuses, only: [:index, :show]
  resources :contests, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campus.rb
class Campus < ApplicationRecord
  belongs_to :region
  has_many :robots, dependent: :destroy

  #==validates

  validates :region_id,    presence: true
  validates :name,         presence: true, length:{ maximum:255 }
  validates :abbreviation, presence: true, length:{ maximum:255 }

  #== scopes

  scope :on_page, -> page { paginate(page: page, per_page: 50) }
  scope :order_default, -> { order(:id) }
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_many :robots, dependent: :destroy

  #==validates

  validates :name, presence: true, length:{ maximum:255 }
  validates :nth,  presence: true, uniqueness: true
  validates :year, presence: true

  #== scopes

  scope :on_page, -> page { paginate(page: page, per_page: 50) }
  scope :order_default, -> { order("nth desc") }
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :campuses, dependent: :destroy

  #==validates

  validates :name, presence: true, length:{ maximum:255 }

end

app/models/robot.rb
class Robot < ApplicationRecord
  belongs_to :contest
  belongs_to :campus

  #==validates

  validates :contest_id, presence: true
  validates :campus_id,  presence: true
  validates :name, allow_blank: true, length:{ maximum:255 }
  validates :kana, allow_blank: true, length:{ maximum:255 }
  validates :team, allow_blank: true, length:{ maximum:255 }, format: { :with => /(A|B)/i }

  #== scopes

  scope :on_page, -> page { paginate(page: page, per_page: 50) }
  scope :order_default, -> { order("contest_id desc, campus_id asc, team asc") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campuses_controller.rb
class CampusesController < ApplicationController
  def index
    @campuses = Campus.order_default.on_page(params[:page])
  end

  def show
    @campus = Campus.find(params[:id])
    @robots = @campus.robots.includes(:contest).order_default.on_page(params[:page])
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = Contest.order_default.on_page(params[:page])
  end

  def show
    @contest = Contest.find(params[:id])
    @robots = @contest.robots.includes(:campus).order_default.on_page(params[:page])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def base_title
    "高専ロボコンデータベース"
  end

  def full_title(page_title = '')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/campuses_helper.rb
module CampusesHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/campuses/index.html.erb
<% provide(:title, "キャンパス一覧") %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @campuses, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>キャンパス</th>
          <th>地区</th>
        </tr>
      </thead>
      <tbody>
        <% @campuses.each do |campus| %>
          <tr>
            <td><%= link_to campus.name, campus %></td>
            <td><%= campus.region.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @campuses, inner_window: 2, outer_window: 0  %>
  </div>
</div>

app/views/campuses/show.html.erb
<% provide(:title, @campus.name) %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>回</th>
          <th>ロボット名</th>
          <th>カナ</th>
          <th>チーム</th>
        </tr>
      </thead>
      <tbody>
        <% @robots.each do |robot| %>
          <tr>
            <td><%= robot.contest.nth %></td>
            <td><%= robot.name %></td>
            <td><%= robot.kana %></td>
            <td><%= robot.team %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <p><%= link_to fa_icon("chevron-left", text: "戻る"), campuses_path %></p>
  </div>
</div>

app/views/contests/index.html.erb
<% provide(:title, "大会一覧") %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contests, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>回</th>
          <th>年</th>
          <th>大会名</th>
        </tr>
      </thead>
      <tbody>
        <% @contests.each do |contest| %>
          <tr>
            <td><%= contest.nth %></td>
            <td><%= contest.year %></td>
            <td><%= link_to contest.name, contest %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @contests, inner_window: 2, outer_window: 0  %>
  </div>
</div>

app/views/contests/show.html.erb
<% provide(:title, @contest.name) %>

<%= render "shared/title", title: (yield :title) %>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>キャンパス</th>
          <th>ロボット名</th>
          <th>カナ</th>
          <th>チーム</th>
        </tr>
      </thead>
      <tbody>
        <% @robots.each do |robot| %>
          <tr>
            <td><%= robot.campus.abbreviation %></td>
            <td><%= robot.name %></td>
            <td><%= robot.kana %></td>
            <td><%= robot.team %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= will_paginate @robots, inner_window: 2, outer_window: 0  %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <p><%= link_to fa_icon("chevron-left", text: "戻る"), contests_path %></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-lg-12">
    <footer>
      <p>&copy; 高専ロボコンデータベース製作委員会</p>
    </footer>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= fa_icon("wrench", text: base_title) %>
        <% end %>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li><%= link_to fa_icon("trophy", text:"大会一覧"), contests_path %></li>
          <li><%= link_to fa_icon("graduation-cap", text:"キャンパス一覧"), campuses_path %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="content">
      <% flash.each do |message_type, message| %>
        <div class="row">
          <div class="col-lg-12">
            <div class="alert alert-<%= alert_type_convert(message_type) %>">
              <%= message %>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
      <div class="row">
        <div class="col-lg-12">
          <p><%= link_to fa_icon("home", text: "HOME"), root_path unless params[:action] == "home" %></p>
        </div>
      </div>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_title.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>
      <%= raw prefix if (defined? prefix) %> <%= title %> <%= raw postfix if (defined? postfix) %>
    </h1>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="bs-component">
      <div class="jumbotron">
        <h1><%= fa_icon("wrench", text: base_title) %></h1>
        <p>キャッチコピーなどをここに記入する</p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h3>このサイトについて</h3>
    <p>このサイトは高専ロボコンを愛する有志により運営されています。</p>
    <p>表示しているロボット名の情報には著作権などの権利は一切生じませんので誰でも自由に複写して使用することができます。</p>
    <p>このサイトで取り扱っている情報には間違いが含まれている可能性が十分にありますが、それよって生じた如何なる損害にも責任は持ちません。</p>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h3>謝辞</h3>
    <p>
      高専ロボコンを愛する皆さんから寄せられた情報を基に、ロボット名のデータベースが2016年に完成しました。
      特に次の方々には多くの協力を頂きました。
      ブロガーの方、木更津、旭川、有明、旧育英などの高専OBの方々、そして高専の学生、教職員、および事務職員の方々。
      さらに高専ロボコンに興味を持つ人が増えていくことを願いつつ、
      ロボット名が何時でも引き出せる機能を備えたこのウェブサイトの開設と運営を以て関係者の方々に深く感謝の意を表したいと思います。
    </p>
    <p class="text-right">
      高専ロボコンデータベース製作委員会
    </p>
  </div>
</div>